### PR TITLE
Make the Ender Crafting JEI wrapper respect shaped crafts

### LINKED ISSUE #28: Shaped Ender Crafting recipes appear in JEI incorrectly
Ingredients to recipes for the Ender Crafter are added as if they are shapeless to JEI. This only impacts the appearance in JEI and its move items functionality. The recipe crafts as it should.

crafttweaker recipe:
```zs
mods.extendedcrafting.EnderCrafting.addShaped(<minecraft:clay>, [
        [<minecraft:gold_ingot>],
        [<minecraft:gold_ingot>], // this should make an L shape
        [<minecraft:gold_ingot>, <minecraft:gold_ingot>, <minecraft:gold_ingot>]
], 5);
```
JEI:
image

### PR DESCRIPTION
**Pull request by WaitingIdly**
code copied from `BasicTableCategory.java`, resolves #28

### CODE REVIEW

File: src/main/java/com/blakebr0/extendedcrafting/compat/jei/endercrafter/EnderCrafterCategory.java [hunk 1]
```diff
@@ -77,13 +78,25 @@ public void setRecipe(IRecipeLayout layout, IRecipeWrapper wrapper, IIngredients
...
+			for (int i = 0; i < shaped.getHeight(); i++) {
+				for (int j = 0; j < shaped.getWidth(); j++) {
+					int index = 1 + (i * 3) + j;
+
+					stacks.set(index, inputs.get(stackIndex));
+
+					stackIndex++;
+				}
+			}
+		} else if (wrapper instanceof TableShapelessWrapper) {
```
Comment (Exaxxion) [inline src/main/java/com/blakebr0/extendedcrafting/compat/jei/endercrafter/EnderCrafterCategory.java:94]: I don't believe there is a need for the `else if` here; a recipe is either shaped or shapeless.

**Comment by Exaxxion** [comment]
Rebase was to put these changes on top of build fixes from master which didn't need to be part of this branch's change history

**Comment by Exaxxion** [comment]
Since this encompassed more than #28 's script snippet would exercise, I'm including the script file I used in the dev environment to make sure shaped recipe construction and rendering in JEI worked properly. Don't forget to rename the file if you use it, GitHub won't let me upload ".zs" even though it's just plaintext.

[test.zs.txt](https://github.com/Nomifactory/ExtendedCrafting/files/11364046/test.zs.txt)

**Review by ALongStringOfNumbers — APPROVED** [review]
